# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json

version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      minor-patch:
        update-types:
          - minor
          - patch
    labels:
      - dependencies
    commit-message:
      prefix: "build"
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - ci
    commit-message:
      prefix: "ci"
